default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: user
      password: password
      port: 5432
      dbname: analytics
      schema: public
      threads: 4
